version: '3.3'

services:
 php:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: php73
  depends_on:
   - db
  image: php:7.3-apache
  volumes:
   - ./php:/var/www/html/
   - ./ressources/apache2.conf:/etc/apache2/apache2.conf
  ports:
   - 80:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: Cyber123
   MYSQL_DATABASE: example
   MYSQL_USER: example
   MYSQL_PASSWORD: example
  volumes:
     - ./ressources/example.sql:/docker-entrypoint-initdb.d/dump.sql
  ports:
   - 3306:3306
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: example
   PMA_PASSWORD: example
   UPLOAD_LIMIT: 20M
  ports:
   - 8899:80
